trigger:
- play_with_azure


pr: none


pool:
  vmImage: 'ubuntu-16.04'


steps:

- bash: |
    sudo apt-get -qq install \
        qt5-default \
        qtbase5-dev  \
        libqt5svg5-dev \
        qttools5-dev \
        qttools5-dev-tools \
        libmuparser-dev \
        libboost-dev \
        libfreetype6-dev \
        libicu-dev \
        pkg-config
  displayName: 'Install dependencies'

- bash: |
    qmake -r librecad.pro CONFIG+=debug_and_release
    make release -j$(nproc)
  displayName: 'Build from source'

- bash: |
    ./scripts/build-appimage.sh
    ls -lh ./AppImage/
  displayName: 'Build AppImage'

- task: CopyFiles@2
  inputs:
    contents: 'AppImage/*.AppImage'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: AppImage

