#
# Azure Pipelines for LibreCAD builds
#


# Branches to monitor
trigger:
- master
- play_with_azure


# Don't run on pull requests
pr: none


stages:

- stage: Build
  displayName: 'Build for all architectures'


  jobs:

  - job: LinuxBuild
    displayName: 'Linux Build'
    condition: False  # disable this job for now

    pool:
      vmImage: 'ubuntu-16.04'

    steps:

    - bash: |
        sudo apt-get -qq install \
            qt5-default \
            qtbase5-dev  \
            libqt5svg5-dev \
            qttools5-dev \
            qttools5-dev-tools \
            libmuparser-dev \
            libboost-dev \
            libfreetype6-dev \
            libicu-dev \
            pkg-config
      displayName: 'Install dependencies'

    - bash: |
        qmake -r librecad.pro CONFIG+=debug_and_release
        make release -j$(nproc)
      displayName: 'Build from source'

    - bash: |
        ./scripts/build-appimage.sh
        ls -lh ./AppImage/
      displayName: 'Build AppImage'

    - task: CopyFiles@2
      inputs:
        contents: 'AppImage/*.AppImage'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: AppImage


  - job: WindowsBuild
    displayName: 'Windows Build'
    condition: False  # disable this job for now

    pool:
      vmImage: 'vs2017-win2016'

    steps:

    - bash: |
        echo 'Dependencies: TODO'
      displayName: 'Install dependencies'

    - bash: |
        echo 'Build: TODO'
      displayName: 'Build from source'

    - task: CopyFiles@2
      inputs:
        contents: '*.exe'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: WindowsInstaller


  - job: MacOSBuild
    displayName: 'MacOS Build'

    pool:
      vmImage: 'macos-10.14'

    steps:

    - bash: |
        brew install \
            boost \
            gcc@4.9 \
            qt5
        brew link qt5 --force
        mkdir -p ~/bin
        ln -s /usr/local/bin/gcc-4.9 ~/bin/gcc
        ln -s /usr/local/bin/g++-4.9 ~/bin/g++
        ln -s /usr/local/bin/gcc-ar-4.9 ~/bin/gcc-ar
        ln -s /usr/local/bin/gcc-nm-4.9 ~/bin/gcc-nm
        ln -s /usr/local/bin/gcc-ranlib-4.9 ~/bin/gcc-ranlib
      displayName: 'Install dependencies'

    - bash: |
        source ~/.bashrc
        gcc --version
        #echo "QT_CONFIG -= no-pkg-config" >> custom.pro
        qmake librecad.pro -r -spec macx-g++ CONFIG+=debug_and_release
        #qmake librecad.pro -r -spec macx-clang CONFIG+=debug_and_release
        make release -j$(sysctl -n hw.ncpu)
        #./scripts/build-osx.sh
        ls -lahR LibreCAD*
      displayName: 'Build from source'

    - task: CopyFiles@2
      inputs:
        contents: '*.dmg'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MacOSPackage


- stage: Upload
  displayName: 'Upload built files'

  jobs:

  - job: UploadFiles
    displayName: 'Upload built files'
    condition: False  # disable this job for now

    pool:
        vmImage: 'ubuntu-16.04'

    steps:

    - bash: |
        echo 'TODO'
      displayName: 'Upload TODO'

