trigger:
- play_with_azure


pr: none


pool:
  vmImage: 'ubuntu-16.04'


steps:

- bash: |
    sudo apt-get -qq install \
        qt5-default \
        qtbase5-dev  \
        libqt5svg5-dev \
        qttools5-dev \
        qttools5-dev-tools \
        libmuparser-dev \
        libboost-dev \
        libfreetype6-dev \
        libicu-dev \
        pkg-config
  displayName: 'Install dependencies'

- bash: |
    qmake -r librecad.pro CONFIG+=debug_and_release
    make release -j$(nproc)
  displayName: 'Build from source'

- bash: |
    ./scripts/build-appimage.sh
  displayName: 'Build AppImage'

#- publish: ./AppImage/LibreCAD*.AppImage
#  artifact: AppImage

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: AppImage

- task: GitHubRelease@0
  inputs:
    gitHubConnection: LibreCAD_Releases
    isPreRelease: true
    addChangeLog: false
    assets: |
        $(Build.ArtifactStagingDirectory)/LibreCAD*.AppImage

